# версия docker-compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    image: postgres:16.1
    restart: always
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # адрес файла, где хранятся переменные окружения
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=proj_db

  redis:
    image: redis:7-alpine

  worker:
    build: .
    restart: always
    entrypoint: [ "celery", "--workdir=.", "-A", "proj", "worker", "--concurrency=1" ]
    volumes:
      - ./proj/:/app

  celery_beat:
    build: .
    restart: always
    entrypoint: [ "celery", "--workdir=.", "-A", "proj", "beat", "-l", "warning", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler" ]
    volumes:
      - ./proj/:/app

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  web:
    build: .
    restart: always
    volumes:
      - ./proj/:/app
    ports:
     - "8000:8000"
    depends_on:
      - db
      - worker

volumes:
  postgres_data: