# Generated by Django 5.1.2 on 2024-11-22 18:34

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код промокода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Укажите процент скидки, например, 10.00 для 10%', max_digits=5, verbose_name='Скидка (%)')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для неограниченного количества использований.', null=True, verbose_name='Максимальное количество использований')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время, с которого код становится активным.', verbose_name='Начало действия')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Дата и время, до которого код активен. Оставьте пустым для бессрочного действия.', null=True, verbose_name='Окончание действия')),
                ('is_active', models.BooleanField(default=True, help_text='Установите в False, чтобы отключить промокод.', verbose_name='Активен')),
                ('users_used', models.ManyToManyField(blank=True, null=True, related_name='used_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, использовавшие код')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
