# Generated by Django 5.1.2 on 2024-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solved_personal_problems',
            field=models.ManyToManyField(related_name='users_who_have_solved', to='courses.personalproblem', verbose_name='Решенные задачи личных курсов'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='solved_problems',
            field=models.ManyToManyField(related_name='users_who_have_solved', to='courses.courseproblem', verbose_name='Решенные задачи'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='solved_tournament_problems',
            field=models.ManyToManyField(related_name='users_who_have_solved', to='courses.tournamentproblem', verbose_name='Решенные задачи турнира'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
