# Generated by Django 5.1.2 on 2024-11-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('courses', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='solved_personal_problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_who_have_solved', to='courses.personalproblem', verbose_name='Решенные задачи личных курсов'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_who_have_solved', to='courses.courseproblem', verbose_name='Решенные задачи'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='solved_tournament_problems',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_who_have_solved', to='courses.tournamentproblem', verbose_name='Решенные задачи турнира'),
        ),
    ]
