# Generated by Django 5.1.2 on 2024-11-06 23:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='tournaments', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
