# Generated by Django 5.1.2 on 2024-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_tournament_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseproblem',
            name='answer1_text',
            field=models.TextField(verbose_name='Текст ответа 1'),
        ),
        migrations.AlterField(
            model_name='courseproblem',
            name='answer2_text',
            field=models.TextField(verbose_name='Текст ответа 2'),
        ),
        migrations.AlterField(
            model_name='courseproblem',
            name='answer3_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа 3'),
        ),
        migrations.AlterField(
            model_name='courseproblem',
            name='answer4_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа 4'),
        ),
        migrations.AlterField(
            model_name='personalproblem',
            name='answer1_text',
            field=models.TextField(verbose_name='Текст ответа 1'),
        ),
        migrations.AlterField(
            model_name='personalproblem',
            name='answer2_text',
            field=models.TextField(verbose_name='Текст ответа 2'),
        ),
        migrations.AlterField(
            model_name='personalproblem',
            name='answer3_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа 3'),
        ),
        migrations.AlterField(
            model_name='personalproblem',
            name='answer4_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа 4'),
        ),
        migrations.AlterField(
            model_name='tournamentproblem',
            name='answer1_text',
            field=models.TextField(verbose_name='Текст ответа 1'),
        ),
        migrations.AlterField(
            model_name='tournamentproblem',
            name='answer2_text',
            field=models.TextField(verbose_name='Текст ответа 2'),
        ),
        migrations.AlterField(
            model_name='tournamentproblem',
            name='answer3_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа 3'),
        ),
        migrations.AlterField(
            model_name='tournamentproblem',
            name='answer4_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ответа 4'),
        ),
    ]
