# Generated by Django 5.1.2 on 2024-11-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseproblem_answer1_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number_of_problems',
        ),
        migrations.RemoveField(
            model_name='personalcourse',
            name='number_of_problems',
        ),
    ]
